#server:
#  port: 0

spring:
  application.name: e-commerce
  output.ansi.enabled: always

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

  jpa:
    hibernate.ddl-auto: create
#    properties.hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: debug